feat: scientificNotationToDecimal + tests
hosseinmd/starkString pull request #18
Opened 2022-11-07 08:48 UTC by farzad-k2003

feature of converting science notation numbers to normal strings was added and tested

2022-11-07 10:47 UTC, hosseinmd commented
LGTM

2022-11-07 10:50 UTC, hosseinmd requested changes

2022-11-07 10:50 UTC, hosseinmd commented on src/core/scientificNotation.ts
> +  if (value == null) return "";
Null is not type of value in StarkString internal value (_value) is always string

2022-11-07 15:35 UTC, merged

2022-11-07 15:36 UTC, hosseinmd commented
Thank you for your contributing.

2022-11-07 16:06 UTC, hosseinmd commented
Released v0.4.4

2022-11-08 05:46 UTC, farzad-k2003 commented
my pleasure